export {
  AccessTokenRequest,
  AccessTokenResponse,
  AccountInfoLookupRequest,
  AccountUpdaterResponse,
  AccountVerificationRequest,
  AchCreditTransaction,
  AchPostAuthTransaction,
  AchPostAuthTransactionAllOf,
  AchPreAuthTransaction,
  AchPreAuthTransactionAllOf,
  AchRecurringType,
  AchResponse,
  AchReturnTransaction,
  AchSaleTransaction,
  AchVoidTransaction,
  ACSResponse,
  AdditionalAmountRate,
  AdditionalDetails,
  AdditionalTransactionDetails,
  Address,
  Airline,
  AirlineAncillaryServiceCategory,
  AirlineTravelRoute,
  AliPay,
  AliPayPaymentMethod,
  AliPayPaymentMethodAllOf,
  AliPaySaleTransaction,
  AliPaySaleTransactionAllOf,
  Amount,
  AmountComponents,
  ApmPaymentMethod,
  ApmPaymentMethodAllOf,
  ApmSaleTransaction,
  ApmSaleTransactionAllOf,
  AuthenticationRequest,
  AuthenticationResult,
  AuthenticationUpdateRequest,
  AVSResponse,
  BancontactQR,
  BasicResponse,
  Billing,
  BillingAddress,
  Card,
  CardFunction,
  CardholderInfoResponse,
  CardInfo,
  CardInfoLookupRequest,
  CardInfoLookupResponse,
  CardVerificationRequest,
  CarRental,
  CarRentalExtraCharges,
  ChinaDomestic,
  ChinaDomesticPaymentMethod,
  ChinaDomesticPaymentMethodAllOf,
  ChinaPnRSaleTransaction,
  ChinaPnRSaleTransactionAllOf,
  ClientLocale,
  ClientRegistration,
  Contact,
  CreatePaymentToken,
  CurrencyConversion,
  CurrencyConversionResponse,
  Customer,
  CustomerAddress,
  Dcc,
  DccAllOf,
  DCCExchangeRateRequest,
  DCCExchangeRateRequestAllOf,
  DecryptedApplePay,
  DecryptedApplePayWalletPaymentMethod,
  DecryptedApplePayWalletPaymentMethodAllOf,
  DecryptedGooglePay,
  DecryptedGooglePayWalletPaymentMethod,
  DecryptedGooglePayWalletPaymentMethodAllOf,
  DecryptedSamsungPay,
  DecryptedSamsungPayWalletPaymentMethod,
  DecryptedSamsungPayWalletPaymentMethodAllOf,
  Device,
  Disbursement,
  DisbursementTransactionType,
  Document,
  DynamicPricing,
  DynamicPricingAllOf,
  DynamicPricingExchangeRateRequest,
  DynamicPricingExchangeRateRequestAllOf,
  EncryptedApplePay,
  EncryptedApplePayHeader,
  EncryptedApplePayWalletPaymentMethod,
  EncryptedApplePayWalletPaymentMethodAllOf,
  EncryptedGooglePay,
  EncryptedGooglePayData,
  EncryptedGooglePayWalletPaymentMethod,
  EncryptedGooglePayWalletPaymentMethodAllOf,
  EncryptedSamsungPay,
  EncryptedSamsungPayWalletPaymentMethod,
  EncryptedSamsungPayWalletPaymentMethodAllOf,
  ErrorDetails,
  ErrorMessage,
  ErrorResponse,
  ExchangeRateDetails,
  ExchangeRateRequest,
  ExchangeRateResponse,
  Expiration,
  FraudAddress,
  FraudOrder,
  FraudOrderItems,
  FraudRegistration,
  FraudRegistrationCard,
  FraudRegistrationDevice,
  FraudRegistrationDeviceItems,
  FraudRegistrationError,
  FraudRegistrationResponse,
  FraudScore,
  Frequency,
  FundingTransactionType,
  IdInfo,
  IndustrySpecificExtensions,
  InstallmentOptions,
  IssuerResponse,
  Items,
  Location,
  Lodging,
  LodgingExtraCharges,
  Loyalty,
  MasterpassWalletPaymentMethod,
  MasterpassWalletPaymentMethodAllOf,
  Mcc6012,
  Merchant,
  Method,
  //ModelInterface,
  Order,
  OrderErrorResponse,
  OrderResponse,
  Payment,
  PaymentBrandResponse,
  PaymentCard,
  PaymentCardCreditTransaction,
  PaymentCardDisbursementTransaction,
  PaymentCardDisbursementTransactionAllOf,
  PaymentCardForcedTicketTransaction,
  PaymentCardForcedTicketTransactionAllOf,
  PaymentCardInfoLookupRequest,
  PaymentCardInfoLookupRequestAllOf,
  PaymentCardPayerAuthTransaction,
  PaymentCardPayerAuthTransactionAllOf,
  PaymentCardPaymentMethod,
  PaymentCardPaymentMethodAllOf,
  PaymentCardPaymentTokenizationRequest,
  PaymentCardPaymentTokenizationRequestAllOf,
  PaymentCardPaymentTokenUpdateRequest,
  PaymentCardPreAuthTransaction,
  PaymentCardPreAuthTransactionAllOf,
  PaymentCardSaleTransaction,
  PaymentCardSaleTransactionAllOf,
  PaymentCardVerificationRequest,
  PaymentCardVerificationRequestAllOf,
  PaymentDevice,
  PaymentDeviceCreditTransaction,
  PaymentDeviceCreditTransactionAllOf,
  PaymentDeviceDisbursementTransaction,
  PaymentDeviceDisbursementTransactionAllOf,
  PaymentDevicePaymentMethod,
  PaymentDevicePaymentMethodAllOf,
  PaymentDevicePaymentTokenizationRequest,
  PaymentDevicePaymentTokenizationRequestAllOf,
  PaymentDevicePreAuthTransaction,
  PaymentDevicePreAuthTransactionAllOf,
  PaymentDeviceSaleTransaction,
  PaymentDeviceSaleTransactionAllOf,
  PaymentFacilitator,
  PaymentMethodDetails,
  PaymentMethodPaymentSchedulesRequest,
  PaymentMethodPaymentSchedulesRequestAllOf,
  PaymentMethodType,
  PaymentRegistration,
  //PaymentPayMethod,
  PaymentSchedulesErrorResponse,
  PaymentSchedulesRequest,
  PaymentSchedulesResponse,
  PaymentStepRequest,
  PaymentStepResponse,
  PaymentTokenCreditTransaction,
  PaymentTokenCreditTransactionAllOf,
  PaymentTokenDetails,
  PaymentTokenDetailsAllOf,
  PaymentTokenDisbursementTransaction,
  PaymentTokenDisbursementTransactionAllOf,
  PaymentTokenInfoLookupRequest,
  PaymentTokenInfoLookupRequestAllOf,
  PaymentTokenizationErrorResponse,
  PaymentTokenizationRequest,
  PaymentTokenizationResponse,
  PaymentTokenPaymentMethod,
  PaymentTokenPaymentMethodAllOf,
  PaymentTokenPreAuthTransaction,
  PaymentTokenPreAuthTransactionAllOf,
  PaymentTokenSaleTransaction,
  PaymentTokenSaleTransactionAllOf,
  PaymentTokenUpdateResponse,
  PaymentTokenVerificationRequest,
  PaymentTokenVerificationRequestAllOf,
  PaymentUrlDetail,
  PaymentUrlDetailResponse,
  PaymentUrlErrorResponse,
  PaymentUrlRequest,
  PaymentUrlResponse,
  PaymentUrlStatus,
  PayPal,
  PaypalCreditTransaction,
  PaypalCreditTransactionAllOf,
  PayPalPaymentMethod,
  PayPalPaymentMethodAllOf,
  Phone,
  PostAuthTransaction,
  PostAuthTransactionAllOf,
  PreAuthSecondaryTransaction,
  PreAuthSecondaryTransactionAllOf,
  PrimaryTransaction,
  ProcessorData,
  ProvideDetailPaymentStepRequest,
  ProvideDetailPaymentStepRequestAllOf,
  ProvideDetailPaymentStepResponse,
  ProvideDetailPaymentStepResponseAllOf,
  PurchaseCards,
  PurchaseCardsLevel2,
  PurchaseCardsLevel3,
  PurchaseCardsLevel3LineItems,
  Receipt,
  ReceiptRequestInfo,
  ReceiverInfo,
  RecurringPaymentDetails,
  RecurringPaymentDetailsResponse,
  ReferencedOrderPaymentSchedulesRequest,
  ReferencedOrderPaymentSchedulesRequestAllOf,
  ReferencedOrderPaymentTokenizationRequest,
  ReferencedOrderPaymentTokenizationRequestAllOf,
  RegistrationMethod,
  ResponseAmountComponents,
  ResponseType,
  ReturnTransaction,
  ReturnTransactionAllOf,
  RevolvingOptions,
  ScoreOnlyRequest,
  ScoreOnlyResponse,
  ScoreOnlyResponseFraudScore,
  ScoreOnlyResponseFraudScoreExplanations,
  SecondaryTransaction,
  Secure3D10AuthenticationRequest,
  Secure3D10AuthenticationRequestAllOf,
  Secure3D10AuthenticationResult,
  Secure3D10AuthenticationResultAllOf,
  Secure3D10AuthenticationUpdateRequest,
  Secure3D10AuthenticationUpdateRequestAllOf,
  Secure3D21AuthenticationRequest,
  Secure3D21AuthenticationRequestAllOf,
  Secure3D21AuthenticationResult,
  Secure3D21AuthenticationResultAllOf,
  Secure3D21AuthenticationUpdateRequest,
  Secure3D21AuthenticationUpdateRequestAllOf,
  Secure3DAuthenticationRequest,
  Secure3DAuthenticationRequestAllOf,
  Secure3DAuthenticationResponse,
  Secure3DAuthenticationResponseParams,
  Secure3DAuthenticationResponseSecure3dMethod,
  Secure3DAuthenticationResult,
  Secure3DAuthenticationResultAllOf,
  Secure3DAuthenticationUpdateRequest,
  Secure3dResponse,
  SenderInfo,
  Sepa,
  SepaMandate,
  SepaPaymentMethod,
  SepaPaymentMethodAllOf,
  SepaSaleTransaction,
  SepaSaleTransactionAllOf,
  Shipping,
  ShipToAddress,
  SoftDescriptor,
  SplitShipment,
  StepRequest,
  StepResponse,
  SubMerchantData,
  SubMerchantSplit,
  TeleCheckAchPaymentMethod,
  TeleCheckAchPaymentMethodAchBillTo,
  TeleCheckCBPPaymentMethod,
  TeleCheckICAPaymentMethod,
  TeleCheckICAPaymentMethodAllOf,
  TransactionErrorResponse,
  TransactionOrigin,
  TransactionResponse,
  TransactionType,
  UnionPayAuthenticationRequest,
  UnionPayAuthenticationRequestAllOf,
  UnionPayAuthenticationUpdateRequest,
  UnionPayAuthenticationUpdateRequestAllOf,
  UpdatePaymentToken,
  UsePaymentToken,
  Verification3ds,
  VerificationAvs,
  VerificationCvv,
  VoidPreAuthTransactions,
  VoidTransaction,
  VoidTransactionAllOf,
  WalletPaymentMethod,
  WalletPreAuthTransaction,
  WalletPreAuthTransactionAllOf,
  WalletSaleTransaction,
  WalletSaleTransactionAllOf,
} from "../openapi/api";

// Wrapper specific models

export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;

export type ApiField<T, P = any> =
  T extends "region" ? {
    // The region where client wants to process the transaction
    region?: string;
  } :
  T extends "authorization" ? {
    // The access token previously generated with the access-tokens call. Use the format &#39;Bearer {access-token}&#39;.
    authorization?: string;
  } :
  T extends "storeId" ? {
    // An optional outlet ID for clients that support multiple stores in the same developer app
    storeId?: string;
  } :
  T extends "orderId" ? {
    // Gateway order identifier as returned in the parameter orderId
    orderId: string;
  } :
  T extends "transactionId" ? {
    // Gateway transaction identifier as returned in the parameter ipgTransactionId
    transactionId: string;
  } :
  T extends "tokenId" ? {
    // Identifies a payment token
    tokenId: string;
  } :
  T extends "paymentUrlId" ? {
    //Identifies Payment URL
    paymentUrlId: string;
  } :
  T extends "transactionTime" ? {
    //Identifies the time of the transaction
    transactionTime: string;
  } :
  T extends "fromDate" ? {
    //Identifies the start date of the URL
    fromDate: string;
  } :
  T extends "toDate" ? {
    //Identifies the end date of the URL
    toDate: string;
  } :
  T extends "merchantTransactionId" ? {
    //Identifies the merchantTransactionId of the URL
    merchantTransactionId: string;
  } :
  T extends "status" ? {
    //Identifies the status of the URL
    status: string;
  } :
  T extends "payload" ? {
    payload: P;
  } : unknown;

