/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.AccessTokenResponse = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AccessTokenResponse model module.
   * @module model/AccessTokenResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AccessTokenResponse</code>.
   * Access Token generation response
   * @alias module:model/AccessTokenResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>AccessTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccessTokenResponse} obj Optional instance to populate.
   * @return {module:model/AccessTokenResponse} The populated <code>AccessTokenResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('accessToken')) {
        obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
      }
      if (data.hasOwnProperty('clientRequestId')) {
        obj['clientRequestId'] = ApiClient.convertToType(data['clientRequestId'], 'String');
      }
      if (data.hasOwnProperty('apiTraceId')) {
        obj['apiTraceId'] = ApiClient.convertToType(data['apiTraceId'], 'String');
      }
      if (data.hasOwnProperty('requestStatus')) {
        obj['requestStatus'] = ApiClient.convertToType(data['requestStatus'], 'String');
      }
    }
    return obj;
  }

  /**
   * Access Token for authentication
   * @member {String} accessToken
   */
  exports.prototype['accessToken'] = undefined;
  /**
   * Echoes back the value from the request header for tracking
   * @member {String} clientRequestId
   */
  exports.prototype['clientRequestId'] = undefined;
  /**
   * Request identifier in API. Use this to request logs from support.
   * @member {String} apiTraceId
   */
  exports.prototype['apiTraceId'] = undefined;
  /**
   * The result of the requested operation. If this is anything other than 'SUCCESS', please refer to the 400s HTTP error codes. See ErrorResponse object for details.
   * @member {module:model/AccessTokenResponse.RequestStatusEnum} requestStatus
   */
  exports.prototype['requestStatus'] = undefined;


  /**
   * Allowed values for the <code>requestStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RequestStatusEnum = {
    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS"  };


  return exports;
}));


