/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AirlineAncillaryServiceCategory model module.
* @module model/AirlineAncillaryServiceCategory
* @version 6.3.0
*/
export default class AirlineAncillaryServiceCategory {
    /**
    * Constructs a new <code>AirlineAncillaryServiceCategory</code>.
    * @alias module:model/AirlineAncillaryServiceCategory
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AirlineAncillaryServiceCategory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AirlineAncillaryServiceCategory} obj Optional instance to populate.
    * @return {module:model/AirlineAncillaryServiceCategory} The populated <code>AirlineAncillaryServiceCategory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AirlineAncillaryServiceCategory();

            
            
            

            if (data.hasOwnProperty('serviceCategory')) {
                obj['serviceCategory'] = ApiClient.convertToType(data['serviceCategory'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AirlineAncillaryServiceCategory.ServiceCategoryEnum} serviceCategory
    */
    serviceCategory = undefined;






    /**
    * Allowed values for the <code>serviceCategory</code> property.
    * @enum {String}
    * @readonly
    */
    static ServiceCategoryEnum = {
    
        /**
         * value: "BUNDLED_SERVICE"
         * @const
         */
        "BUNDLED_SERVICE": "BUNDLED_SERVICE",
    
        /**
         * value: "BAGGAGE_FEE"
         * @const
         */
        "BAGGAGE_FEE": "BAGGAGE_FEE",
    
        /**
         * value: "CHANGE_FEE"
         * @const
         */
        "CHANGE_FEE": "CHANGE_FEE",
    
        /**
         * value: "CARGO"
         * @const
         */
        "CARGO": "CARGO",
    
        /**
         * value: "CARBON_OFFSET"
         * @const
         */
        "CARBON_OFFSET": "CARBON_OFFSET",
    
        /**
         * value: "FREQUENT_FLYER"
         * @const
         */
        "FREQUENT_FLYER": "FREQUENT_FLYER",
    
        /**
         * value: "GIFT_CARD"
         * @const
         */
        "GIFT_CARD": "GIFT_CARD",
    
        /**
         * value: "GROUND_TRANSPORT"
         * @const
         */
        "GROUND_TRANSPORT": "GROUND_TRANSPORT",
    
        /**
         * value: "IN_FLIGHT_ENTERTAINMENT"
         * @const
         */
        "IN_FLIGHT_ENTERTAINMENT": "IN_FLIGHT_ENTERTAINMENT",
    
        /**
         * value: "LOUNGE"
         * @const
         */
        "LOUNGE": "LOUNGE",
    
        /**
         * value: "MEDICAL"
         * @const
         */
        "MEDICAL": "MEDICAL",
    
        /**
         * value: "MEAL_BEVERAGE"
         * @const
         */
        "MEAL_BEVERAGE": "MEAL_BEVERAGE",
    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER": "OTHER",
    
        /**
         * value: "PASSENGER_ASSIST_FEE"
         * @const
         */
        "PASSENGER_ASSIST_FEE": "PASSENGER_ASSIST_FEE",
    
        /**
         * value: "PETS"
         * @const
         */
        "PETS": "PETS",
    
        /**
         * value: "SEAT_FEES"
         * @const
         */
        "SEAT_FEES": "SEAT_FEES",
    
        /**
         * value: "STANDBY"
         * @const
         */
        "STANDBY": "STANDBY",
    
        /**
         * value: "SERVICE_FEE"
         * @const
         */
        "SERVICE_FEE": "SERVICE_FEE",
    
        /**
         * value: "STORE"
         * @const
         */
        "STORE": "STORE",
    
        /**
         * value: "TRAVEL_SERVICE"
         * @const
         */
        "TRAVEL_SERVICE": "TRAVEL_SERVICE",
    
        /**
         * value: "UNACCOMPANIED_TRAVEL"
         * @const
         */
        "UNACCOMPANIED_TRAVEL": "UNACCOMPANIED_TRAVEL",
    
        /**
         * value: "UPGRADES"
         * @const
         */
        "UPGRADES": "UPGRADES",
    
        /**
         * value: "WI_FI"
         * @const
         */
        "WI_FI": "WI_FI"    
    };



}


