/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AmountComponents'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AmountComponents'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.Amount = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.AmountComponents);
  }
}(this, function(ApiClient, AmountComponents) {
  'use strict';




  /**
   * The Amount model module.
   * @module model/Amount
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Amount</code>.
   * @alias module:model/Amount
   * @class
   * @param total {Number} 
   * @param currency {String} ISO 4217 currency code (http://en.wikipedia.org/wiki/ISO_4217).
   */
  var exports = function(total, currency) {
    var _this = this;

    _this['total'] = total;
    _this['currency'] = currency;

  };

  /**
   * Constructs a <code>Amount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Amount} obj Optional instance to populate.
   * @return {module:model/Amount} The populated <code>Amount</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('currency')) {
        obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
      }
      if (data.hasOwnProperty('components')) {
        obj['components'] = AmountComponents.constructFromObject(data['components']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * ISO 4217 currency code (http://en.wikipedia.org/wiki/ISO_4217).
   * @member {String} currency
   */
  exports.prototype['currency'] = undefined;
  /**
   * @member {module:model/AmountComponents} components
   */
  exports.prototype['components'] = undefined;



  return exports;
}));


