/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.AmountComponents = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AmountComponents model module.
   * @module model/AmountComponents
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AmountComponents</code>.
   * @alias module:model/AmountComponents
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>AmountComponents</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AmountComponents} obj Optional instance to populate.
   * @return {module:model/AmountComponents} The populated <code>AmountComponents</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('subtotal')) {
        obj['subtotal'] = ApiClient.convertToType(data['subtotal'], 'Number');
      }
      if (data.hasOwnProperty('vatAmount')) {
        obj['vatAmount'] = ApiClient.convertToType(data['vatAmount'], 'Number');
      }
      if (data.hasOwnProperty('localTax')) {
        obj['localTax'] = ApiClient.convertToType(data['localTax'], 'Number');
      }
      if (data.hasOwnProperty('shipping')) {
        obj['shipping'] = ApiClient.convertToType(data['shipping'], 'Number');
      }
      if (data.hasOwnProperty('cashback')) {
        obj['cashback'] = ApiClient.convertToType(data['cashback'], 'Number');
      }
      if (data.hasOwnProperty('tip')) {
        obj['tip'] = ApiClient.convertToType(data['tip'], 'Number');
      }
      if (data.hasOwnProperty('convenienceFee')) {
        obj['convenienceFee'] = ApiClient.convertToType(data['convenienceFee'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} subtotal
   */
  exports.prototype['subtotal'] = undefined;
  /**
   * @member {Number} vatAmount
   */
  exports.prototype['vatAmount'] = undefined;
  /**
   * @member {Number} localTax
   */
  exports.prototype['localTax'] = undefined;
  /**
   * @member {Number} shipping
   */
  exports.prototype['shipping'] = undefined;
  /**
   * @member {Number} cashback
   */
  exports.prototype['cashback'] = undefined;
  /**
   * @member {Number} tip
   */
  exports.prototype['tip'] = undefined;
  /**
   * @member {Number} convenienceFee
   */
  exports.prototype['convenienceFee'] = undefined;



  return exports;
}));


