/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthenticationResponseVerification model module.
* @module model/AuthenticationResponseVerification
* @version 6.3.0
*/
export default class AuthenticationResponseVerification {
    /**
    * Constructs a new <code>AuthenticationResponseVerification</code>.
    * @alias module:model/AuthenticationResponseVerification
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AuthenticationResponseVerification</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthenticationResponseVerification} obj Optional instance to populate.
    * @return {module:model/AuthenticationResponseVerification} The populated <code>AuthenticationResponseVerification</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticationResponseVerification();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('MD')) {
                obj['MD'] = ApiClient.convertToType(data['MD'], 'String');
            }
            if (data.hasOwnProperty('PaRes')) {
                obj['PaRes'] = ApiClient.convertToType(data['PaRes'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AuthenticationResponseVerification.TypeEnum} type
    */
    type = undefined;
    /**
    * @member {String} MD
    */
    MD = undefined;
    /**
    * @member {String} PaRes
    */
    PaRes = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "SECURE_3D"
         * @const
         */
        "3D": "SECURE_3D"    
    };



}


