/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.BasketItem = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.Amount);
  }
}(this, function(ApiClient, Amount) {
  'use strict';




  /**
   * The BasketItem model module.
   * @module model/BasketItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>BasketItem</code>.
   * @alias module:model/BasketItem
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>BasketItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BasketItem} obj Optional instance to populate.
   * @return {module:model/BasketItem} The populated <code>BasketItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('unitPrice')) {
        obj['unitPrice'] = Amount.constructFromObject(data['unitPrice']);
      }
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Item ID
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Referenced parent Business Entity ID in master database for the outlets // COPY-PASTE ERROR?
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:model/Amount} unitPrice
   */
  exports.prototype['unitPrice'] = undefined;
  /**
   * Total quantity of items
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;



  return exports;
}));


