/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Address from './Address';
import Contact from './Contact';





/**
* The Billing model module.
* @module model/Billing
* @version 6.3.0
*/
export default class Billing {
    /**
    * Constructs a new <code>Billing</code>.
    * @alias module:model/Billing
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Billing</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Billing} obj Optional instance to populate.
    * @return {module:model/Billing} The populated <code>Billing</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Billing();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('personalNumber')) {
                obj['personalNumber'] = ApiClient.convertToType(data['personalNumber'], 'String');
            }
            if (data.hasOwnProperty('birthDate')) {
                obj['birthDate'] = ApiClient.convertToType(data['birthDate'], 'Date');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} personalNumber
    */
    personalNumber = undefined;
    /**
    * @member {Date} birthDate
    */
    birthDate = undefined;
    /**
    * @member {module:model/Billing.GenderEnum} gender
    */
    gender = undefined;
    /**
    * @member {module:model/Contact} contact
    */
    contact = undefined;
    /**
    * @member {module:model/Address} address
    */
    address = undefined;






    /**
    * Allowed values for the <code>gender</code> property.
    * @enum {String}
    * @readonly
    */
    static GenderEnum = {
    
        /**
         * value: "MALE"
         * @const
         */
        "MALE": "MALE",
    
        /**
         * value: "FEMALE"
         * @const
         */
        "FEMALE": "FEMALE",
    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN": "UNKNOWN"    
    };



}


