/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaymentMethod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaymentMethod'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.CardVerificationsTransaction = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.PaymentMethod);
  }
}(this, function(ApiClient, PaymentMethod) {
  'use strict';




  /**
   * The CardVerificationsTransaction model module.
   * @module model/CardVerificationsTransaction
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CardVerificationsTransaction</code>.
   * Model for card verifcation transactions
   * @alias module:model/CardVerificationsTransaction
   * @class
   * @param paymentMethod {module:model/PaymentMethod} 
   */
  var exports = function(paymentMethod) {
    var _this = this;


    _this['paymentMethod'] = paymentMethod;
  };

  /**
   * Constructs a <code>CardVerificationsTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CardVerificationsTransaction} obj Optional instance to populate.
   * @return {module:model/CardVerificationsTransaction} The populated <code>CardVerificationsTransaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('storeId')) {
        obj['storeId'] = ApiClient.convertToType(data['storeId'], 'String');
      }
      if (data.hasOwnProperty('paymentMethod')) {
        obj['paymentMethod'] = PaymentMethod.constructFromObject(data['paymentMethod']);
      }
    }
    return obj;
  }

  /**
   * Optional Outlet ID for clients that support multiple store in the same app
   * @member {String} storeId
   */
  exports.prototype['storeId'] = undefined;
  /**
   * @member {module:model/PaymentMethod} paymentMethod
   */
  exports.prototype['paymentMethod'] = undefined;



  return exports;
}));


