/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CarRentalExtraCharges'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CarRentalExtraCharges'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.CarRental = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.CarRentalExtraCharges);
  }
}(this, function(ApiClient, CarRentalExtraCharges) {
  'use strict';




  /**
   * The CarRental model module.
   * @module model/CarRental
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CarRental</code>.
   * @alias module:model/CarRental
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>CarRental</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarRental} obj Optional instance to populate.
   * @return {module:model/CarRental} The populated <code>CarRental</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('agreementNumber')) {
        obj['agreementNumber'] = ApiClient.convertToType(data['agreementNumber'], 'String');
      }
      if (data.hasOwnProperty('renterName')) {
        obj['renterName'] = ApiClient.convertToType(data['renterName'], 'String');
      }
      if (data.hasOwnProperty('returnCity')) {
        obj['returnCity'] = ApiClient.convertToType(data['returnCity'], 'String');
      }
      if (data.hasOwnProperty('returnDate')) {
        obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
      }
      if (data.hasOwnProperty('pickupDate')) {
        obj['pickupDate'] = ApiClient.convertToType(data['pickupDate'], 'Date');
      }
      if (data.hasOwnProperty('rentalClassId')) {
        obj['rentalClassId'] = ApiClient.convertToType(data['rentalClassId'], 'String');
      }
      if (data.hasOwnProperty('extraCharges')) {
        obj['extraCharges'] = ApiClient.convertToType(data['extraCharges'], [CarRentalExtraCharges]);
      }
      if (data.hasOwnProperty('noShowIndicator')) {
        obj['noShowIndicator'] = ApiClient.convertToType(data['noShowIndicator'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} agreementNumber
   */
  exports.prototype['agreementNumber'] = undefined;
  /**
   * @member {String} renterName
   */
  exports.prototype['renterName'] = undefined;
  /**
   * @member {String} returnCity
   */
  exports.prototype['returnCity'] = undefined;
  /**
   * @member {Date} returnDate
   */
  exports.prototype['returnDate'] = undefined;
  /**
   * @member {Date} pickupDate
   */
  exports.prototype['pickupDate'] = undefined;
  /**
   * @member {String} rentalClassId
   */
  exports.prototype['rentalClassId'] = undefined;
  /**
   * @member {Array.<module:model/CarRentalExtraCharges>} extraCharges
   */
  exports.prototype['extraCharges'] = undefined;
  /**
   * @member {Boolean} noShowIndicator
   */
  exports.prototype['noShowIndicator'] = undefined;



  return exports;
}));


