/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CarRentalExtraCharges from './CarRentalExtraCharges';





/**
* The CarRental model module.
* @module model/CarRental
* @version 6.3.0
*/
export default class CarRental {
    /**
    * Constructs a new <code>CarRental</code>.
    * @alias module:model/CarRental
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>CarRental</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CarRental} obj Optional instance to populate.
    * @return {module:model/CarRental} The populated <code>CarRental</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CarRental();

            
            
            

            if (data.hasOwnProperty('agreementNumber')) {
                obj['agreementNumber'] = ApiClient.convertToType(data['agreementNumber'], 'String');
            }
            if (data.hasOwnProperty('renterName')) {
                obj['renterName'] = ApiClient.convertToType(data['renterName'], 'String');
            }
            if (data.hasOwnProperty('returnCity')) {
                obj['returnCity'] = ApiClient.convertToType(data['returnCity'], 'String');
            }
            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
            }
            if (data.hasOwnProperty('pickupDate')) {
                obj['pickupDate'] = ApiClient.convertToType(data['pickupDate'], 'Date');
            }
            if (data.hasOwnProperty('rentalClassId')) {
                obj['rentalClassId'] = ApiClient.convertToType(data['rentalClassId'], 'String');
            }
            if (data.hasOwnProperty('extraCharges')) {
                obj['extraCharges'] = ApiClient.convertToType(data['extraCharges'], [CarRentalExtraCharges]);
            }
            if (data.hasOwnProperty('noShowIndicator')) {
                obj['noShowIndicator'] = ApiClient.convertToType(data['noShowIndicator'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} agreementNumber
    */
    agreementNumber = undefined;
    /**
    * @member {String} renterName
    */
    renterName = undefined;
    /**
    * @member {String} returnCity
    */
    returnCity = undefined;
    /**
    * @member {Date} returnDate
    */
    returnDate = undefined;
    /**
    * @member {Date} pickupDate
    */
    pickupDate = undefined;
    /**
    * @member {String} rentalClassId
    */
    rentalClassId = undefined;
    /**
    * @member {Array.<module:model/CarRentalExtraCharges>} extraCharges
    */
    extraCharges = undefined;
    /**
    * @member {Boolean} noShowIndicator
    */
    noShowIndicator = undefined;








}


