/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.CarRentalExtraCharges = factory(root.FirstApiSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CarRentalExtraCharges model module.
   * @module model/CarRentalExtraCharges
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>CarRentalExtraCharges</code>.
   * @alias module:model/CarRentalExtraCharges
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>CarRentalExtraCharges</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarRentalExtraCharges} obj Optional instance to populate.
   * @return {module:model/CarRentalExtraCharges} The populated <code>CarRentalExtraCharges</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('chargeItem')) {
        obj['chargeItem'] = ApiClient.convertToType(data['chargeItem'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CarRentalExtraCharges.ChargeItemEnum} chargeItem
   */
  exports.prototype['chargeItem'] = undefined;


  /**
   * Allowed values for the <code>chargeItem</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ChargeItemEnum = {
    /**
     * value: "EXTRA_MILEAGE"
     * @const
     */
    "EXTRA_MILEAGE": "EXTRA_MILEAGE",
    /**
     * value: "GAS"
     * @const
     */
    "GAS": "GAS",
    /**
     * value: "LATE_RETURN"
     * @const
     */
    "LATE_RETURN": "LATE_RETURN",
    /**
     * value: "ONE_WAY_SERVICE_FEE"
     * @const
     */
    "ONE_WAY_SERVICE_FEE": "ONE_WAY_SERVICE_FEE",
    /**
     * value: "PARKING_VIOLATION"
     * @const
     */
    "PARKING_VIOLATION": "PARKING_VIOLATION"  };


  return exports;
}));


