/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Error from './Error';
import ResponseType from './ResponseType';





/**
* The ErrorResponse model module.
* @module model/ErrorResponse
* @version 6.3.0
*/
export default class ErrorResponse {
    /**
    * Constructs a new <code>ErrorResponse</code>.
    * Response containing error information.
    * @alias module:model/ErrorResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorResponse} obj Optional instance to populate.
    * @return {module:model/ErrorResponse} The populated <code>ErrorResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorResponse();

            
            
            

            if (data.hasOwnProperty('clientRequestId')) {
                obj['clientRequestId'] = ApiClient.convertToType(data['clientRequestId'], 'String');
            }
            if (data.hasOwnProperty('apiTraceId')) {
                obj['apiTraceId'] = ApiClient.convertToType(data['apiTraceId'], 'String');
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ResponseType.constructFromObject(data['responseType']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = Error.constructFromObject(data['error']);
            }
        }
        return obj;
    }

    /**
    * Echoes back the value from the request header for tracking
    * @member {String} clientRequestId
    */
    clientRequestId = undefined;
    /**
    * Request identifier in API. Use this to request logs from support.
    * @member {String} apiTraceId
    */
    apiTraceId = undefined;
    /**
    * The schema type returned in the response.
    * @member {module:model/ResponseType} responseType
    */
    responseType = undefined;
    /**
    * @member {module:model/Error} error
    */
    error = undefined;








}


