/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error', 'model/ResponseType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Error'), require('./ResponseType'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.ErrorResponse = factory(root.FirstApiSdk.ApiClient, root.FirstApiSdk.Error, root.FirstApiSdk.ResponseType);
  }
}(this, function(ApiClient, Error, ResponseType) {
  'use strict';




  /**
   * The ErrorResponse model module.
   * @module model/ErrorResponse
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>ErrorResponse</code>.
   * Response containing error information.
   * @alias module:model/ErrorResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorResponse} obj Optional instance to populate.
   * @return {module:model/ErrorResponse} The populated <code>ErrorResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('clientRequestId')) {
        obj['clientRequestId'] = ApiClient.convertToType(data['clientRequestId'], 'String');
      }
      if (data.hasOwnProperty('apiTraceId')) {
        obj['apiTraceId'] = ApiClient.convertToType(data['apiTraceId'], 'String');
      }
      if (data.hasOwnProperty('responseType')) {
        obj['responseType'] = ResponseType.constructFromObject(data['responseType']);
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = Error.constructFromObject(data['error']);
      }
    }
    return obj;
  }

  /**
   * Echoes back the value from the request header for tracking
   * @member {String} clientRequestId
   */
  exports.prototype['clientRequestId'] = undefined;
  /**
   * Request identifier in API. Use this to request logs from support.
   * @member {String} apiTraceId
   */
  exports.prototype['apiTraceId'] = undefined;
  /**
   * The schema type returned in the response.
   * @member {module:model/ResponseType} responseType
   */
  exports.prototype['responseType'] = undefined;
  /**
   * @member {module:model/Error} error
   */
  exports.prototype['error'] = undefined;



  return exports;
}));


