/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ErrorDetails from './ErrorDetails';





/**
* The Error model module.
* @module model/Error
* @version 6.3.0
*/
export default class Error {
    /**
    * Constructs a new <code>Error</code>.
    * Error information.
    * @alias module:model/Error
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Error} obj Optional instance to populate.
    * @return {module:model/Error} The populated <code>Error</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Error();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], [ErrorDetails]);
            }
        }
        return obj;
    }

    /**
    * Uniquely identifies an error condition. Client applications need to read and handle errors based on this.
    * @member {String} code
    */
    code = undefined;
    /**
    * A generic description of the error condition.
    * @member {String} message
    */
    message = undefined;
    /**
    * Detailed information about message format errors.
    * @member {Array.<module:model/ErrorDetails>} details
    */
    details = undefined;








}


