/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.Frequency = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Frequency model module.
   * @module model/Frequency
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Frequency</code>.
   * The frequency of payments.
   * @alias module:model/Frequency
   * @class
   * @param every {Number} Rate of frequency.
   * @param unit {module:model/Frequency.UnitEnum} Unit which defines the frequency.
   */
  var exports = function(every, unit) {
    var _this = this;

    _this['every'] = every;
    _this['unit'] = unit;
  };

  /**
   * Constructs a <code>Frequency</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Frequency} obj Optional instance to populate.
   * @return {module:model/Frequency} The populated <code>Frequency</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('every')) {
        obj['every'] = ApiClient.convertToType(data['every'], 'Number');
      }
      if (data.hasOwnProperty('unit')) {
        obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
      }
    }
    return obj;
  }

  /**
   * Rate of frequency.
   * @member {Number} every
   */
  exports.prototype['every'] = undefined;
  /**
   * Unit which defines the frequency.
   * @member {module:model/Frequency.UnitEnum} unit
   */
  exports.prototype['unit'] = undefined;


  /**
   * Allowed values for the <code>unit</code> property.
   * @enum {String}
   * @readonly
   */
  exports.UnitEnum = {
    /**
     * value: "DAY"
     * @const
     */
    "DAY": "DAY",
    /**
     * value: "WEEK"
     * @const
     */
    "WEEK": "WEEK",
    /**
     * value: "MONTH"
     * @const
     */
    "MONTH": "MONTH",
    /**
     * value: "YEAR"
     * @const
     */
    "YEAR": "YEAR"  };


  return exports;
}));


