/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Airline', 'model/CarRental', 'model/Lodging'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Airline'), require('./CarRental'), require('./Lodging'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.IndustrySpecificExtensions = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.Airline, root.FirstDataGateway.CarRental, root.FirstDataGateway.Lodging);
  }
}(this, function(ApiClient, Airline, CarRental, Lodging) {
  'use strict';




  /**
   * The IndustrySpecificExtensions model module.
   * @module model/IndustrySpecificExtensions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>IndustrySpecificExtensions</code>.
   * @alias module:model/IndustrySpecificExtensions
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>IndustrySpecificExtensions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IndustrySpecificExtensions} obj Optional instance to populate.
   * @return {module:model/IndustrySpecificExtensions} The populated <code>IndustrySpecificExtensions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('airline')) {
        obj['airline'] = Airline.constructFromObject(data['airline']);
      }
      if (data.hasOwnProperty('lodging')) {
        obj['lodging'] = Lodging.constructFromObject(data['lodging']);
      }
      if (data.hasOwnProperty('carRental')) {
        obj['carRental'] = CarRental.constructFromObject(data['carRental']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Airline} airline
   */
  exports.prototype['airline'] = undefined;
  /**
   * @member {module:model/Lodging} lodging
   */
  exports.prototype['lodging'] = undefined;
  /**
   * @member {module:model/CarRental} carRental
   */
  exports.prototype['carRental'] = undefined;



  return exports;
}));


