/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The LodgingExtraCharges model module.
* @module model/LodgingExtraCharges
* @version 6.3.0
*/
export default class LodgingExtraCharges {
    /**
    * Constructs a new <code>LodgingExtraCharges</code>.
    * @alias module:model/LodgingExtraCharges
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>LodgingExtraCharges</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LodgingExtraCharges} obj Optional instance to populate.
    * @return {module:model/LodgingExtraCharges} The populated <code>LodgingExtraCharges</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LodgingExtraCharges();

            
            
            

            if (data.hasOwnProperty('chargeItem')) {
                obj['chargeItem'] = ApiClient.convertToType(data['chargeItem'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/LodgingExtraCharges.ChargeItemEnum} chargeItem
    */
    chargeItem = undefined;






    /**
    * Allowed values for the <code>chargeItem</code> property.
    * @enum {String}
    * @readonly
    */
    static ChargeItemEnum = {
    
        /**
         * value: "GIFT_SHOP"
         * @const
         */
        "GIFT_SHOP": "GIFT_SHOP",
    
        /**
         * value: "LAUNDRY"
         * @const
         */
        "LAUNDRY": "LAUNDRY",
    
        /**
         * value: "MINI_BAR"
         * @const
         */
        "MINI_BAR": "MINI_BAR",
    
        /**
         * value: "RESTAURANT"
         * @const
         */
        "RESTAURANT": "RESTAURANT",
    
        /**
         * value: "TELEPHONE"
         * @const
         */
        "TELEPHONE": "TELEPHONE",
    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER": "OTHER"    
    };



}


