/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.LodgingExtraCharges = factory(root.FirstApiSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LodgingExtraCharges model module.
   * @module model/LodgingExtraCharges
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>LodgingExtraCharges</code>.
   * @alias module:model/LodgingExtraCharges
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>LodgingExtraCharges</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LodgingExtraCharges} obj Optional instance to populate.
   * @return {module:model/LodgingExtraCharges} The populated <code>LodgingExtraCharges</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('chargeItem')) {
        obj['chargeItem'] = ApiClient.convertToType(data['chargeItem'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/LodgingExtraCharges.ChargeItemEnum} chargeItem
   */
  exports.prototype['chargeItem'] = undefined;


  /**
   * Allowed values for the <code>chargeItem</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ChargeItemEnum = {
    /**
     * value: "GIFT_SHOP"
     * @const
     */
    "GIFT_SHOP": "GIFT_SHOP",
    /**
     * value: "LAUNDRY"
     * @const
     */
    "LAUNDRY": "LAUNDRY",
    /**
     * value: "MINI_BAR"
     * @const
     */
    "MINI_BAR": "MINI_BAR",
    /**
     * value: "RESTAURANT"
     * @const
     */
    "RESTAURANT": "RESTAURANT",
    /**
     * value: "TELEPHONE"
     * @const
     */
    "TELEPHONE": "TELEPHONE",
    /**
     * value: "OTHER"
     * @const
     */
    "OTHER": "OTHER"  };


  return exports;
}));


