/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LodgingExtraCharges'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LodgingExtraCharges'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.Lodging = factory(root.FirstApiSdk.ApiClient, root.FirstApiSdk.LodgingExtraCharges);
  }
}(this, function(ApiClient, LodgingExtraCharges) {
  'use strict';




  /**
   * The Lodging model module.
   * @module model/Lodging
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>Lodging</code>.
   * @alias module:model/Lodging
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Lodging</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Lodging} obj Optional instance to populate.
   * @return {module:model/Lodging} The populated <code>Lodging</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('arrivalDate')) {
        obj['arrivalDate'] = ApiClient.convertToType(data['arrivalDate'], 'Date');
      }
      if (data.hasOwnProperty('departureDate')) {
        obj['departureDate'] = ApiClient.convertToType(data['departureDate'], 'Date');
      }
      if (data.hasOwnProperty('folioNumber')) {
        obj['folioNumber'] = ApiClient.convertToType(data['folioNumber'], 'String');
      }
      if (data.hasOwnProperty('extraCharges')) {
        obj['extraCharges'] = ApiClient.convertToType(data['extraCharges'], [LodgingExtraCharges]);
      }
      if (data.hasOwnProperty('noShowIndicator')) {
        obj['noShowIndicator'] = ApiClient.convertToType(data['noShowIndicator'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Date of arrival
   * @member {Date} arrivalDate
   */
  exports.prototype['arrivalDate'] = undefined;
  /**
   * Date of departure
   * @member {Date} departureDate
   */
  exports.prototype['departureDate'] = undefined;
  /**
   * Portfolio number
   * @member {String} folioNumber
   */
  exports.prototype['folioNumber'] = undefined;
  /**
   * @member {Array.<module:model/LodgingExtraCharges>} extraCharges
   */
  exports.prototype['extraCharges'] = undefined;
  /**
   * @member {Boolean} noShowIndicator
   */
  exports.prototype['noShowIndicator'] = undefined;



  return exports;
}));


