/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Billing', 'model/Shipping'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Billing'), require('./Shipping'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.Order = factory(root.FirstApiSdk.ApiClient, root.FirstApiSdk.Billing, root.FirstApiSdk.Shipping);
  }
}(this, function(ApiClient, Billing, Shipping) {
  'use strict';




  /**
   * The Order model module.
   * @module model/Order
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('billing')) {
        obj['billing'] = Billing.constructFromObject(data['billing']);
      }
      if (data.hasOwnProperty('shipping')) {
        obj['shipping'] = Shipping.constructFromObject(data['shipping']);
      }
    }
    return obj;
  }

  /**
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {module:model/Billing} billing
   */
  exports.prototype['billing'] = undefined;
  /**
   * @member {module:model/Shipping} shipping
   */
  exports.prototype['shipping'] = undefined;



  return exports;
}));


