/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Billing from './Billing';
import Shipping from './Shipping';





/**
* The Order model module.
* @module model/Order
* @version 6.3.0
*/
export default class Order {
    /**
    * Constructs a new <code>Order</code>.
    * @alias module:model/Order
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Order} obj Optional instance to populate.
    * @return {module:model/Order} The populated <code>Order</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();

            
            
            

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('billing')) {
                obj['billing'] = Billing.constructFromObject(data['billing']);
            }
            if (data.hasOwnProperty('shipping')) {
                obj['shipping'] = Shipping.constructFromObject(data['shipping']);
            }
        }
        return obj;
    }

    /**
    * @member {String} orderId
    */
    orderId = undefined;
    /**
    * @member {module:model/Billing} billing
    */
    billing = undefined;
    /**
    * @member {module:model/Shipping} shipping
    */
    shipping = undefined;








}


