/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.PaymentUrlResponse = factory(root.FirstApiSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PaymentUrlResponse model module.
   * @module model/PaymentUrlResponse
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>PaymentUrlResponse</code>.
   * Response from embedded payment link request.
   * @alias module:model/PaymentUrlResponse
   * @class
   * @param clientRequestId {String} Echoes back the value in the Request header for tracking.
   * @param apiTraceId {String} Request identifier in API, can be used to request logs from the support.
   * @param requestStatus {module:model/PaymentUrlResponse.RequestStatusEnum} Request status. If it's anything other than 'SUCCESS', please refer to 400s HTTP error codes or decline. See Error object for details.
   */
  var exports = function(clientRequestId, apiTraceId, requestStatus) {
    var _this = this;

    _this['clientRequestId'] = clientRequestId;
    _this['apiTraceId'] = apiTraceId;
    _this['requestStatus'] = requestStatus;



  };

  /**
   * Constructs a <code>PaymentUrlResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentUrlResponse} obj Optional instance to populate.
   * @return {module:model/PaymentUrlResponse} The populated <code>PaymentUrlResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('clientRequestId')) {
        obj['clientRequestId'] = ApiClient.convertToType(data['clientRequestId'], 'String');
      }
      if (data.hasOwnProperty('apiTraceId')) {
        obj['apiTraceId'] = ApiClient.convertToType(data['apiTraceId'], 'String');
      }
      if (data.hasOwnProperty('requestStatus')) {
        obj['requestStatus'] = ApiClient.convertToType(data['requestStatus'], 'String');
      }
      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('paymentUrl')) {
        obj['paymentUrl'] = ApiClient.convertToType(data['paymentUrl'], 'String');
      }
      if (data.hasOwnProperty('transactionId')) {
        obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
      }
    }
    return obj;
  }

  /**
   * Echoes back the value in the Request header for tracking.
   * @member {String} clientRequestId
   */
  exports.prototype['clientRequestId'] = undefined;
  /**
   * Request identifier in API, can be used to request logs from the support.
   * @member {String} apiTraceId
   */
  exports.prototype['apiTraceId'] = undefined;
  /**
   * Request status. If it's anything other than 'SUCCESS', please refer to 400s HTTP error codes or decline. See Error object for details.
   * @member {module:model/PaymentUrlResponse.RequestStatusEnum} requestStatus
   */
  exports.prototype['requestStatus'] = undefined;
  /**
   * Client Order ID if supplied by client, otherwise the Order ID.
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {String} paymentUrl
   */
  exports.prototype['paymentUrl'] = undefined;
  /**
   * ID code from the transaction.
   * @member {String} transactionId
   */
  exports.prototype['transactionId'] = undefined;


  /**
   * Allowed values for the <code>requestStatus</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RequestStatusEnum = {
    /**
     * value: "SUCCESS"
     * @const
     */
    "SUCCESS": "SUCCESS",
    /**
     * value: "VALIDATION_FAILED"
     * @const
     */
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    /**
     * value: "PROCESSING_FAILED"
     * @const
     */
    "PROCESSING_FAILED": "PROCESSING_FAILED",
    /**
     * value: "FAILURE"
     * @const
     */
    "FAILURE": "FAILURE"  };


  return exports;
}));


