/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PaymentCardAuthenticationResult model module.
* @module model/PaymentCardAuthenticationResult
* @version 6.3.0
*/
export default class PaymentCardAuthenticationResult {
    /**
    * Constructs a new <code>PaymentCardAuthenticationResult</code>.
    * Submit the result of the authentication managed outside of The Gateway. For more convenient usage without implementing 3-D Secure yourself see \&quot;authenticationRequest\&quot; section
    * @alias module:model/PaymentCardAuthenticationResult
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaymentCardAuthenticationResult</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentCardAuthenticationResult} obj Optional instance to populate.
    * @return {module:model/PaymentCardAuthenticationResult} The populated <code>PaymentCardAuthenticationResult</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCardAuthenticationResult();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('verificationResponse')) {
                obj['verificationResponse'] = ApiClient.convertToType(data['verificationResponse'], 'String');
            }
            if (data.hasOwnProperty('payerAuthenticationResponse')) {
                obj['payerAuthenticationResponse'] = ApiClient.convertToType(data['payerAuthenticationResponse'], 'String');
            }
            if (data.hasOwnProperty('authenticationValue')) {
                obj['authenticationValue'] = ApiClient.convertToType(data['authenticationValue'], 'String');
            }
            if (data.hasOwnProperty('xid')) {
                obj['xid'] = ApiClient.convertToType(data['xid'], 'String');
            }
        }
        return obj;
    }

    /**
    * Type of authentication result. For example, 3-D Secure.
    * @member {module:model/PaymentCardAuthenticationResult.TypeEnum} type
    */
    type = undefined;
    /**
    * Card enrollment result from the Verification Response (VeRes)
    * @member {module:model/PaymentCardAuthenticationResult.VerificationResponseEnum} verificationResponse
    */
    verificationResponse = undefined;
    /**
    * Payer authentication result from Payment Authentication Response (PaRes)
    * @member {module:model/PaymentCardAuthenticationResult.PayerAuthenticationResponseEnum} payerAuthenticationResponse
    */
    payerAuthenticationResponse = undefined;
    /**
    * Cardholder Authentication Verification Value (CAVV)
    * @member {String} authenticationValue
    */
    authenticationValue = undefined;
    /**
    * Authentication ID
    * @member {String} xid
    */
    xid = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "SECURE_3D"
         * @const
         */
        "3D": "SECURE_3D"    
    };

    /**
    * Allowed values for the <code>verificationResponse</code> property.
    * @enum {String}
    * @readonly
    */
    static VerificationResponseEnum = {
    
        /**
         * value: "Y"
         * @const
         */
        "Y": "Y",
    
        /**
         * value: "N"
         * @const
         */
        "N": "N",
    
        /**
         * value: "U"
         * @const
         */
        "U": "U"    
    };

    /**
    * Allowed values for the <code>payerAuthenticationResponse</code> property.
    * @enum {String}
    * @readonly
    */
    static PayerAuthenticationResponseEnum = {
    
        /**
         * value: "Y"
         * @const
         */
        "Y": "Y",
    
        /**
         * value: "N"
         * @const
         */
        "N": "N",
    
        /**
         * value: "U"
         * @const
         */
        "U": "U",
    
        /**
         * value: "A"
         * @const
         */
        "A": "A"    
    };



}


