/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.PaymentCardAuthenticationResult = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PaymentCardAuthenticationResult model module.
   * @module model/PaymentCardAuthenticationResult
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PaymentCardAuthenticationResult</code>.
   * Submit the result of the authentication managed outside of The Gateway. For more convenient usage without implementing 3-D Secure yourself see \&quot;authenticationRequest\&quot; section
   * @alias module:model/PaymentCardAuthenticationResult
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>PaymentCardAuthenticationResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentCardAuthenticationResult} obj Optional instance to populate.
   * @return {module:model/PaymentCardAuthenticationResult} The populated <code>PaymentCardAuthenticationResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('verificationResponse')) {
        obj['verificationResponse'] = ApiClient.convertToType(data['verificationResponse'], 'String');
      }
      if (data.hasOwnProperty('payerAuthenticationResponse')) {
        obj['payerAuthenticationResponse'] = ApiClient.convertToType(data['payerAuthenticationResponse'], 'String');
      }
      if (data.hasOwnProperty('authenticationValue')) {
        obj['authenticationValue'] = ApiClient.convertToType(data['authenticationValue'], 'String');
      }
      if (data.hasOwnProperty('xid')) {
        obj['xid'] = ApiClient.convertToType(data['xid'], 'String');
      }
    }
    return obj;
  }

  /**
   * Type of authentication result. For example, 3-D Secure.
   * @member {module:model/PaymentCardAuthenticationResult.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Card enrollment result from the Verification Response (VeRes)
   * @member {module:model/PaymentCardAuthenticationResult.VerificationResponseEnum} verificationResponse
   */
  exports.prototype['verificationResponse'] = undefined;
  /**
   * Payer authentication result from Payment Authentication Response (PaRes)
   * @member {module:model/PaymentCardAuthenticationResult.PayerAuthenticationResponseEnum} payerAuthenticationResponse
   */
  exports.prototype['payerAuthenticationResponse'] = undefined;
  /**
   * Cardholder Authentication Verification Value (CAVV)
   * @member {String} authenticationValue
   */
  exports.prototype['authenticationValue'] = undefined;
  /**
   * Authentication ID
   * @member {String} xid
   */
  exports.prototype['xid'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "SECURE_3D"
     * @const
     */
    "3D": "SECURE_3D"  };

  /**
   * Allowed values for the <code>verificationResponse</code> property.
   * @enum {String}
   * @readonly
   */
  exports.VerificationResponseEnum = {
    /**
     * value: "Y"
     * @const
     */
    "Y": "Y",
    /**
     * value: "N"
     * @const
     */
    "N": "N",
    /**
     * value: "U"
     * @const
     */
    "U": "U"  };

  /**
   * Allowed values for the <code>payerAuthenticationResponse</code> property.
   * @enum {String}
   * @readonly
   */
  exports.PayerAuthenticationResponseEnum = {
    /**
     * value: "Y"
     * @const
     */
    "Y": "Y",
    /**
     * value: "N"
     * @const
     */
    "N": "N",
    /**
     * value: "U"
     * @const
     */
    "U": "U",
    /**
     * value: "A"
     * @const
     */
    "A": "A"  };


  return exports;
}));


