/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PaymentCardAuthenticationRequest model module.
* @module model/PaymentCardAuthenticationRequest
* @version 6.3.0
*/
export default class PaymentCardAuthenticationRequest {
    /**
    * Constructs a new <code>PaymentCardAuthenticationRequest</code>.
    * Request authentication of the card (typically, 3-D Secure) to verify the cardholder and be eligible for liability shift
    * @alias module:model/PaymentCardAuthenticationRequest
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PaymentCardAuthenticationRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentCardAuthenticationRequest} obj Optional instance to populate.
    * @return {module:model/PaymentCardAuthenticationRequest} The populated <code>PaymentCardAuthenticationRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCardAuthenticationRequest();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Indicates what kind of authentication scheme the merchant wants to use on the card. Currently, only 3-D Secure is supported.
    * @member {module:model/PaymentCardAuthenticationRequest.TypeEnum} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "SECURE_3D"
         * @const
         */
        "3D": "SECURE_3D"    
    };



}


