/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Amount from './Amount';
import ClientLocale from './ClientLocale';





/**
* The PaymentUrlRequest model module.
* @module model/PaymentUrlRequest
* @version 6.3.0
*/
export default class PaymentUrlRequest {
    /**
    * Constructs a new <code>PaymentUrlRequest</code>.
    * Request to generate an embedded payment link.
    * @alias module:model/PaymentUrlRequest
    * @class
    * @param storeId {String} An optional outlet id for clients that support multiple store in the same developer app.
    * @param amount {module:model/Amount} 
    * @param orderId {String} Client Order ID if supplied by client, otherwise the Order ID.
    */

    constructor(storeId, amount, orderId) {
        

        
        

        this['storeId'] = storeId;this['amount'] = amount;this['orderId'] = orderId;

        
    }

    /**
    * Constructs a <code>PaymentUrlRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentUrlRequest} obj Optional instance to populate.
    * @return {module:model/PaymentUrlRequest} The populated <code>PaymentUrlRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentUrlRequest();

            
            
            

            if (data.hasOwnProperty('storeId')) {
                obj['storeId'] = ApiClient.convertToType(data['storeId'], 'String');
            }
            if (data.hasOwnProperty('clientLocale')) {
                obj['clientLocale'] = ClientLocale.constructFromObject(data['clientLocale']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
        }
        return obj;
    }

    /**
    * An optional outlet id for clients that support multiple store in the same developer app.
    * @member {String} storeId
    */
    storeId = undefined;
    /**
    * @member {module:model/ClientLocale} clientLocale
    */
    clientLocale = undefined;
    /**
    * @member {module:model/Amount} amount
    */
    amount = undefined;
    /**
    * Client Order ID if supplied by client, otherwise the Order ID.
    * @member {String} orderId
    */
    orderId = undefined;








}


