/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.PaymentCardAuthenticationRequest = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PaymentCardAuthenticationRequest model module.
   * @module model/PaymentCardAuthenticationRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PaymentCardAuthenticationRequest</code>.
   * Request authentication of the card (typically, 3-D Secure) to verify the cardholder and be eligible for liability shift
   * @alias module:model/PaymentCardAuthenticationRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>PaymentCardAuthenticationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentCardAuthenticationRequest} obj Optional instance to populate.
   * @return {module:model/PaymentCardAuthenticationRequest} The populated <code>PaymentCardAuthenticationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * Indicates what kind of authentication scheme the merchant wants to use on the card. Currently, only 3-D Secure is supported.
   * @member {module:model/PaymentCardAuthenticationRequest.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "SECURE_3D"
     * @const
     */
    "3D": "SECURE_3D"  };


  return exports;
}));


