/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Expiration from './Expiration';
import PaymentCardAuthenticationRequest from './PaymentCardAuthenticationRequest';
import PaymentCardAuthenticationResult from './PaymentCardAuthenticationResult';





/**
* The PaymentCard model module.
* @module model/PaymentCard
* @version 6.3.0
*/
export default class PaymentCard {
    /**
    * Constructs a new <code>PaymentCard</code>.
    * @alias module:model/PaymentCard
    * @class
    * @param _number {String} Payment card number
    */

    constructor(_number) {
        

        
        

        this['number'] = _number;

        
    }

    /**
    * Constructs a <code>PaymentCard</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PaymentCard} obj Optional instance to populate.
    * @return {module:model/PaymentCard} The populated <code>PaymentCard</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCard();

            
            
            

            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'String');
            }
            if (data.hasOwnProperty('expiryDate')) {
                obj['expiryDate'] = Expiration.constructFromObject(data['expiryDate']);
            }
            if (data.hasOwnProperty('securityCode')) {
                obj['securityCode'] = ApiClient.convertToType(data['securityCode'], 'String');
            }
            if (data.hasOwnProperty('cardFunction')) {
                obj['cardFunction'] = ApiClient.convertToType(data['cardFunction'], 'String');
            }
            if (data.hasOwnProperty('cardholderName')) {
                obj['cardholderName'] = ApiClient.convertToType(data['cardholderName'], 'String');
            }
            if (data.hasOwnProperty('authenticationRequest')) {
                obj['authenticationRequest'] = PaymentCardAuthenticationRequest.constructFromObject(data['authenticationRequest']);
            }
            if (data.hasOwnProperty('authenticationResult')) {
                obj['authenticationResult'] = PaymentCardAuthenticationResult.constructFromObject(data['authenticationResult']);
            }
            if (data.hasOwnProperty('brand')) {
                obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
            }
        }
        return obj;
    }

    /**
    * Payment card number
    * @member {String} number
    */
    number = undefined;
    /**
    * @member {module:model/Expiration} expiryDate
    */
    expiryDate = undefined;
    /**
    * CVV
    * @member {String} securityCode
    */
    securityCode = undefined;
    /**
    * @member {module:model/PaymentCard.CardFunctionEnum} cardFunction
    * @default 'CREDIT'
    */
    cardFunction = 'CREDIT';
    /**
    * @member {String} cardholderName
    */
    cardholderName = undefined;
    /**
    * @member {module:model/PaymentCardAuthenticationRequest} authenticationRequest
    */
    authenticationRequest = undefined;
    /**
    * @member {module:model/PaymentCardAuthenticationResult} authenticationResult
    */
    authenticationResult = undefined;
    /**
    * Optional, required only if using dual branded card
    * @member {String} brand
    */
    brand = undefined;






    /**
    * Allowed values for the <code>cardFunction</code> property.
    * @enum {String}
    * @readonly
    */
    static CardFunctionEnum = {
    
        /**
         * value: "CREDIT"
         * @const
         */
        "CREDIT": "CREDIT",
    
        /**
         * value: "DEBIT"
         * @const
         */
        "DEBIT": "DEBIT"    
    };



}


