/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.PayPal = factory(root.FirstApiSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PayPal model module.
   * @module model/PayPal
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>PayPal</code>.
   * The payment object for PayPal transactions. The recipientEmail element is required for this payment type.
   * @alias module:model/PayPal
   * @class
   * @param recipientEmail {String} Email address of the recipient
   */
  var exports = function(recipientEmail) {
    var _this = this;

    _this['recipientEmail'] = recipientEmail;
  };

  /**
   * Constructs a <code>PayPal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PayPal} obj Optional instance to populate.
   * @return {module:model/PayPal} The populated <code>PayPal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('recipientEmail')) {
        obj['recipientEmail'] = ApiClient.convertToType(data['recipientEmail'], 'String');
      }
    }
    return obj;
  }

  /**
   * Email address of the recipient
   * @member {String} recipientEmail
   */
  exports.prototype['recipientEmail'] = undefined;



  return exports;
}));


