/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PayPal model module.
* @module model/PayPal
* @version 6.3.0
*/
export default class PayPal {
    /**
    * Constructs a new <code>PayPal</code>.
    * The payment object for PayPal transactions. The recipientEmail element is required for this payment type.
    * @alias module:model/PayPal
    * @class
    * @param recipientEmail {String} Email address of the recipient
    */

    constructor(recipientEmail) {
        

        
        

        this['recipientEmail'] = recipientEmail;

        
    }

    /**
    * Constructs a <code>PayPal</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PayPal} obj Optional instance to populate.
    * @return {module:model/PayPal} The populated <code>PayPal</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayPal();

            
            
            

            if (data.hasOwnProperty('recipientEmail')) {
                obj['recipientEmail'] = ApiClient.convertToType(data['recipientEmail'], 'String');
            }
        }
        return obj;
    }

    /**
    * Email address of the recipient
    * @member {String} recipientEmail
    */
    recipientEmail = undefined;








}


