/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InstallmentOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InstallmentOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstApiSdk) {
      root.FirstApiSdk = {};
    }
    root.FirstApiSdk.PrimaryTransactionAdditionalDetails = factory(root.FirstApiSdk.ApiClient, root.FirstApiSdk.InstallmentOptions);
  }
}(this, function(ApiClient, InstallmentOptions) {
  'use strict';




  /**
   * The PrimaryTransactionAdditionalDetails model module.
   * @module model/PrimaryTransactionAdditionalDetails
   * @version 6.3.0
   */

  /**
   * Constructs a new <code>PrimaryTransactionAdditionalDetails</code>.
   * @alias module:model/PrimaryTransactionAdditionalDetails
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>PrimaryTransactionAdditionalDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrimaryTransactionAdditionalDetails} obj Optional instance to populate.
   * @return {module:model/PrimaryTransactionAdditionalDetails} The populated <code>PrimaryTransactionAdditionalDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('referenceNumber')) {
        obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
      }
      if (data.hasOwnProperty('comments')) {
        obj['comments'] = ApiClient.convertToType(data['comments'], 'String');
      }
      if (data.hasOwnProperty('dynamicMerchantName')) {
        obj['dynamicMerchantName'] = ApiClient.convertToType(data['dynamicMerchantName'], 'String');
      }
      if (data.hasOwnProperty('invoiceNumber')) {
        obj['invoiceNumber'] = ApiClient.convertToType(data['invoiceNumber'], 'String');
      }
      if (data.hasOwnProperty('purchaseOrderNumber')) {
        obj['purchaseOrderNumber'] = ApiClient.convertToType(data['purchaseOrderNumber'], 'String');
      }
      if (data.hasOwnProperty('recurringType')) {
        obj['recurringType'] = ApiClient.convertToType(data['recurringType'], 'String');
      }
      if (data.hasOwnProperty('installmentOptions')) {
        obj['installmentOptions'] = InstallmentOptions.constructFromObject(data['installmentOptions']);
      }
    }
    return obj;
  }

  /**
   * For FORCED_TICKET only. Stores the six digit reference number you have received as the result of a successful external authorization (e.g. by phone). The Gateway needs this number for uniquely mapping a ForcedTicket transaction to a previously performed external authorization.] 
   * @member {String} referenceNumber
   */
  exports.prototype['referenceNumber'] = undefined;
  /**
   * @member {String} comments
   */
  exports.prototype['comments'] = undefined;
  /**
   * @member {String} dynamicMerchantName
   */
  exports.prototype['dynamicMerchantName'] = undefined;
  /**
   * @member {String} invoiceNumber
   */
  exports.prototype['invoiceNumber'] = undefined;
  /**
   * @member {String} purchaseOrderNumber
   */
  exports.prototype['purchaseOrderNumber'] = undefined;
  /**
   * Valid values are 'FIRST', 'REPEAT' and 'STANDING_INSTRUCTION'.
   * @member {String} recurringType
   */
  exports.prototype['recurringType'] = undefined;
  /**
   * @member {module:model/InstallmentOptions} installmentOptions
   */
  exports.prototype['installmentOptions'] = undefined;



  return exports;
}));


