/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class ResponseType.
* @enum {}
* @readonly
*/
export default class ResponseType {
    
        /**
         * value: "BadRequest"
         * @const
         */
        BadRequest = "BadRequest";

    
        /**
         * value: "Unauthenticated"
         * @const
         */
        Unauthenticated = "Unauthenticated";

    
        /**
         * value: "Unauthorized"
         * @const
         */
        Unauthorized = "Unauthorized";

    
        /**
         * value: "NotFound"
         * @const
         */
        NotFound = "NotFound";

    
        /**
         * value: "GatewayDeclined"
         * @const
         */
        GatewayDeclined = "GatewayDeclined";

    
        /**
         * value: "EndpointDeclined"
         * @const
         */
        EndpointDeclined = "EndpointDeclined";

    
        /**
         * value: "ServerError"
         * @const
         */
        ServerError = "ServerError";

    
        /**
         * value: "EndpointCommunicationError"
         * @const
         */
        EndpointCommunicationError = "EndpointCommunicationError";

    

    /**
    * Returns a <code>ResponseType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ResponseType} The enum <code>ResponseType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


