/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Amount from './Amount';
import SplitShipment from './SplitShipment';





/**
* The SecondaryTransaction model module.
* @module model/SecondaryTransaction
* @version 6.3.0
*/
export default class SecondaryTransaction {
    /**
    * Constructs a new <code>SecondaryTransaction</code>.
    * @alias module:model/SecondaryTransaction
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SecondaryTransaction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SecondaryTransaction} obj Optional instance to populate.
    * @return {module:model/SecondaryTransaction} The populated <code>SecondaryTransaction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecondaryTransaction();

            
            
            

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = Amount.constructFromObject(data['amount']);
            }
            if (data.hasOwnProperty('splitShipment')) {
                obj['splitShipment'] = SplitShipment.constructFromObject(data['splitShipment']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Amount} amount
    */
    amount = undefined;
    /**
    * @member {module:model/SplitShipment} splitShipment
    */
    splitShipment = undefined;








}


