/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Amount', 'model/SplitShipment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Amount'), require('./SplitShipment'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.SecondaryTransaction = factory(root.FirstDataGateway.ApiClient, root.FirstDataGateway.Amount, root.FirstDataGateway.SplitShipment);
  }
}(this, function(ApiClient, Amount, SplitShipment) {
  'use strict';




  /**
   * The SecondaryTransaction model module.
   * @module model/SecondaryTransaction
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SecondaryTransaction</code>.
   * @alias module:model/SecondaryTransaction
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SecondaryTransaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SecondaryTransaction} obj Optional instance to populate.
   * @return {module:model/SecondaryTransaction} The populated <code>SecondaryTransaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = Amount.constructFromObject(data['amount']);
      }
      if (data.hasOwnProperty('splitShipment')) {
        obj['splitShipment'] = SplitShipment.constructFromObject(data['splitShipment']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Amount} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {module:model/SplitShipment} splitShipment
   */
  exports.prototype['splitShipment'] = undefined;



  return exports;
}));


