/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SepaMandate model module.
* @module model/SepaMandate
* @version 6.3.0
*/
export default class SepaMandate {
    /**
    * Constructs a new <code>SepaMandate</code>.
    * @alias module:model/SepaMandate
    * @class
    * @param reference {String} Existing mandate reference, managed by merchant. Must match [A-Za-z0-9:?/+(),. -]{1,35} and not start with two slashes (“//”). Also known as the Mandate ID
    * @param url {String} Valid URL pointing to the SEPA mandate (PDF / HTML format recommended)
    * @param signatureDate {Date} Date of mandate signature.
    * @param type {module:model/SepaMandate.TypeEnum} Sequence type of the direct debit. This defaults to 'SINGLE' if not provided.
    */

    constructor(reference, url, signatureDate, type) {
        

        
        

        this['reference'] = reference;this['url'] = url;this['signatureDate'] = signatureDate;this['type'] = type;

        
    }

    /**
    * Constructs a <code>SepaMandate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SepaMandate} obj Optional instance to populate.
    * @return {module:model/SepaMandate} The populated <code>SepaMandate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SepaMandate();

            
            
            

            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('signatureDate')) {
                obj['signatureDate'] = ApiClient.convertToType(data['signatureDate'], 'Date');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * Existing mandate reference, managed by merchant. Must match [A-Za-z0-9:?/+(),. -]{1,35} and not start with two slashes (“//”). Also known as the Mandate ID
    * @member {String} reference
    */
    reference = undefined;
    /**
    * Valid URL pointing to the SEPA mandate (PDF / HTML format recommended)
    * @member {String} url
    */
    url = undefined;
    /**
    * Date of mandate signature.
    * @member {Date} signatureDate
    */
    signatureDate = undefined;
    /**
    * Sequence type of the direct debit. This defaults to 'SINGLE' if not provided.
    * @member {module:model/SepaMandate.TypeEnum} type
    * @default 'SINGLE'
    */
    type = 'SINGLE';






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "SINGLE"
         * @const
         */
        "SINGLE": "SINGLE",
    
        /**
         * value: "FIRST_COLLECTION"
         * @const
         */
        "FIRST_COLLECTION": "FIRST_COLLECTION",
    
        /**
         * value: "RECURRING_COLLECTION"
         * @const
         */
        "RECURRING_COLLECTION": "RECURRING_COLLECTION",
    
        /**
         * value: "FINAL_COLLECTION"
         * @const
         */
        "FINAL_COLLECTION": "FINAL_COLLECTION"    
    };



}


