/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SepaMandate from './SepaMandate';





/**
* The Sepa model module.
* @module model/Sepa
* @version 6.3.0
*/
export default class Sepa {
    /**
    * Constructs a new <code>Sepa</code>.
    * The payment object for SEPA DD. The iban, billing_address.name and country elements are required for this payment type.
    * @alias module:model/Sepa
    * @class
    * @param iban {String} Bank account in IBAN format
    * @param name {String} The name of the payer
    * @param country {String} Country of residence of the payer using the ISO 3166 standard (http://en.wikipedia.org/wiki/ISO_3166)
    * @param mandate {module:model/SepaMandate} 
    */

    constructor(iban, name, country, mandate) {
        

        
        

        this['iban'] = iban;this['name'] = name;this['country'] = country;this['mandate'] = mandate;

        
    }

    /**
    * Constructs a <code>Sepa</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Sepa} obj Optional instance to populate.
    * @return {module:model/Sepa} The populated <code>Sepa</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Sepa();

            
            
            

            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('mandate')) {
                obj['mandate'] = SepaMandate.constructFromObject(data['mandate']);
            }
        }
        return obj;
    }

    /**
    * Bank account in IBAN format
    * @member {String} iban
    */
    iban = undefined;
    /**
    * The name of the payer
    * @member {String} name
    */
    name = undefined;
    /**
    * Country of residence of the payer using the ISO 3166 standard (http://en.wikipedia.org/wiki/ISO_3166)
    * @member {String} country
    */
    country = undefined;
    /**
    * The email address of the payer
    * @member {String} email
    */
    email = undefined;
    /**
    * @member {module:model/SepaMandate} mandate
    */
    mandate = undefined;








}


