/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Address from './Address';
import Contact from './Contact';





/**
* The Shipping model module.
* @module model/Shipping
* @version 6.3.0
*/
export default class Shipping {
    /**
    * Constructs a new <code>Shipping</code>.
    * @alias module:model/Shipping
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Shipping</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Shipping} obj Optional instance to populate.
    * @return {module:model/Shipping} The populated <code>Shipping</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Shipping();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = Contact.constructFromObject(data['contact']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {module:model/Contact} contact
    */
    contact = undefined;
    /**
    * @member {module:model/Address} address
    */
    address = undefined;








}


