/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class TransactionType.
* @enum {}
* @readonly
*/
export default class TransactionType {
    
        /**
         * value: "SALE"
         * @const
         */
        SALE = "SALE";

    
        /**
         * value: "PREAUTH"
         * @const
         */
        PREAUTH = "PREAUTH";

    
        /**
         * value: "CREDIT"
         * @const
         */
        CREDIT = "CREDIT";

    
        /**
         * value: "FORCED_TICKET"
         * @const
         */
        FORCED_TICKET = "FORCED_TICKET";

    
        /**
         * value: "VOID"
         * @const
         */
        VOID = "VOID";

    
        /**
         * value: "RETURN"
         * @const
         */
        RETURN = "RETURN";

    
        /**
         * value: "POSTAUTH"
         * @const
         */
        POSTAUTH = "POSTAUTH";

    

    /**
    * Returns a <code>TransactionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TransactionType} The enum <code>TransactionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


