/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FirstDataGateway) {
      root.FirstDataGateway = {};
    }
    root.FirstDataGateway.TransactionResponseAuthenticationRedirectParams = factory(root.FirstDataGateway.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TransactionResponseAuthenticationRedirectParams model module.
   * @module model/TransactionResponseAuthenticationRedirectParams
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TransactionResponseAuthenticationRedirectParams</code>.
   * @alias module:model/TransactionResponseAuthenticationRedirectParams
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TransactionResponseAuthenticationRedirectParams</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionResponseAuthenticationRedirectParams} obj Optional instance to populate.
   * @return {module:model/TransactionResponseAuthenticationRedirectParams} The populated <code>TransactionResponseAuthenticationRedirectParams</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('PaReq')) {
        obj['PaReq'] = ApiClient.convertToType(data['PaReq'], 'String');
      }
      if (data.hasOwnProperty('TermUrl')) {
        obj['TermUrl'] = ApiClient.convertToType(data['TermUrl'], 'String');
      }
      if (data.hasOwnProperty('MD')) {
        obj['MD'] = ApiClient.convertToType(data['MD'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} PaReq
   */
  exports.prototype['PaReq'] = undefined;
  /**
   * @member {String} TermUrl
   */
  exports.prototype['TermUrl'] = undefined;
  /**
   * @member {String} MD
   */
  exports.prototype['MD'] = undefined;



  return exports;
}));


