/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TransactionResponseAuthenticationRedirectParams from './TransactionResponseAuthenticationRedirectParams';





/**
* The TransactionResponseAuthenticationRedirect model module.
* @module model/TransactionResponseAuthenticationRedirect
* @version 6.3.0
*/
export default class TransactionResponseAuthenticationRedirect {
    /**
    * Constructs a new <code>TransactionResponseAuthenticationRedirect</code>.
    * @alias module:model/TransactionResponseAuthenticationRedirect
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TransactionResponseAuthenticationRedirect</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TransactionResponseAuthenticationRedirect} obj Optional instance to populate.
    * @return {module:model/TransactionResponseAuthenticationRedirect} The populated <code>TransactionResponseAuthenticationRedirect</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionResponseAuthenticationRedirect();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('targetUrl')) {
                obj['targetUrl'] = ApiClient.convertToType(data['targetUrl'], 'String');
            }
            if (data.hasOwnProperty('params')) {
                obj['params'] = TransactionResponseAuthenticationRedirectParams.constructFromObject(data['params']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TransactionResponseAuthenticationRedirect.TypeEnum} type
    */
    type = undefined;
    /**
    * @member {String} targetUrl
    */
    targetUrl = undefined;
    /**
    * @member {module:model/TransactionResponseAuthenticationRedirectParams} params
    */
    params = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "SECURE_3D"
         * @const
         */
        "3D": "SECURE_3D"    
    };



}


