/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstApiSdk);
  }
}(this, function(expect, FirstApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstApiSdk.AirlineTravelRoute();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AirlineTravelRoute', function() {
    it('should create an instance of AirlineTravelRoute', function() {
      // uncomment below and update the code to test AirlineTravelRoute
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be.a(FirstApiSdk.AirlineTravelRoute);
    });

    it('should have the property departureDate (base name: "departureDate")', function() {
      // uncomment below and update the code to test the property departureDate
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property origin (base name: "origin")', function() {
      // uncomment below and update the code to test the property origin
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property destination (base name: "destination")', function() {
      // uncomment below and update the code to test the property destination
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property carrierCode (base name: "carrierCode")', function() {
      // uncomment below and update the code to test the property carrierCode
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property serviceClass (base name: "serviceClass")', function() {
      // uncomment below and update the code to test the property serviceClass
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property stopoverType (base name: "stopoverType")', function() {
      // uncomment below and update the code to test the property stopoverType
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property fareBasisCode (base name: "fareBasisCode")', function() {
      // uncomment below and update the code to test the property fareBasisCode
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property departureTax (base name: "departureTax")', function() {
      // uncomment below and update the code to test the property departureTax
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

    it('should have the property flightNumber (base name: "flightNumber")', function() {
      // uncomment below and update the code to test the property flightNumber
      //var instane = new FirstApiSdk.AirlineTravelRoute();
      //expect(instance).to.be();
    });

  });

}));
