/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstApiSdk);
  }
}(this, function(expect, FirstApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstApiSdk.CarRental();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CarRental', function() {
    it('should create an instance of CarRental', function() {
      // uncomment below and update the code to test CarRental
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be.a(FirstApiSdk.CarRental);
    });

    it('should have the property agreementNumber (base name: "agreementNumber")', function() {
      // uncomment below and update the code to test the property agreementNumber
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property renterName (base name: "renterName")', function() {
      // uncomment below and update the code to test the property renterName
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property returnCity (base name: "returnCity")', function() {
      // uncomment below and update the code to test the property returnCity
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property returnDate (base name: "returnDate")', function() {
      // uncomment below and update the code to test the property returnDate
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property pickupDate (base name: "pickupDate")', function() {
      // uncomment below and update the code to test the property pickupDate
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property rentalClassId (base name: "rentalClassId")', function() {
      // uncomment below and update the code to test the property rentalClassId
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property extraCharges (base name: "extraCharges")', function() {
      // uncomment below and update the code to test the property extraCharges
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

    it('should have the property noShowIndicator (base name: "noShowIndicator")', function() {
      // uncomment below and update the code to test the property noShowIndicator
      //var instane = new FirstApiSdk.CarRental();
      //expect(instance).to.be();
    });

  });

}));
