/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstApiSdk);
  }
}(this, function(expect, FirstApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PrimaryTransactionAdditionalDetails', function() {
    it('should create an instance of PrimaryTransactionAdditionalDetails', function() {
      // uncomment below and update the code to test PrimaryTransactionAdditionalDetails
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be.a(FirstApiSdk.PrimaryTransactionAdditionalDetails);
    });

    it('should have the property referenceNumber (base name: "referenceNumber")', function() {
      // uncomment below and update the code to test the property referenceNumber
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property comments (base name: "comments")', function() {
      // uncomment below and update the code to test the property comments
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property dynamicMerchantName (base name: "dynamicMerchantName")', function() {
      // uncomment below and update the code to test the property dynamicMerchantName
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "invoiceNumber")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property purchaseOrderNumber (base name: "purchaseOrderNumber")', function() {
      // uncomment below and update the code to test the property purchaseOrderNumber
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property recurringType (base name: "recurringType")', function() {
      // uncomment below and update the code to test the property recurringType
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

    it('should have the property installmentOptions (base name: "installmentOptions")', function() {
      // uncomment below and update the code to test the property installmentOptions
      //var instane = new FirstApiSdk.PrimaryTransactionAdditionalDetails();
      //expect(instance).to.be();
    });

  });

}));
