/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstDataGateway);
  }
}(this, function(expect, FirstDataGateway) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstDataGateway.ProcessorData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessorData', function() {
    it('should create an instance of ProcessorData', function() {
      // uncomment below and update the code to test ProcessorData
      //var instane = new FirstDataGateway.ProcessorData();
      //expect(instance).to.be.a(FirstDataGateway.ProcessorData);
    });

    it('should have the property responseCode (base name: "responseCode")', function() {
      // uncomment below and update the code to test the property responseCode
      //var instane = new FirstDataGateway.ProcessorData();
      //expect(instance).to.be();
    });

    it('should have the property responseMessage (base name: "responseMessage")', function() {
      // uncomment below and update the code to test the property responseMessage
      //var instane = new FirstDataGateway.ProcessorData();
      //expect(instance).to.be();
    });

    it('should have the property approvalCode (base name: "approvalCode")', function() {
      // uncomment below and update the code to test the property approvalCode
      //var instane = new FirstDataGateway.ProcessorData();
      //expect(instance).to.be();
    });

  });

}));
