/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstApiSdk);
  }
}(this, function(expect, FirstApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstApiSdk.StoredCredential();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StoredCredential', function() {
    it('should create an instance of StoredCredential', function() {
      // uncomment below and update the code to test StoredCredential
      //var instane = new FirstApiSdk.StoredCredential();
      //expect(instance).to.be.a(FirstApiSdk.StoredCredential);
    });

    it('should have the property sequence (base name: "sequence")', function() {
      // uncomment below and update the code to test the property sequence
      //var instane = new FirstApiSdk.StoredCredential();
      //expect(instance).to.be();
    });

    it('should have the property scheduled (base name: "scheduled")', function() {
      // uncomment below and update the code to test the property scheduled
      //var instane = new FirstApiSdk.StoredCredential();
      //expect(instance).to.be();
    });

    it('should have the property referencedSchemeTransactionId (base name: "referencedSchemeTransactionId")', function() {
      // uncomment below and update the code to test the property referencedSchemeTransactionId
      //var instane = new FirstApiSdk.StoredCredential();
      //expect(instance).to.be();
    });

    it('should have the property initiator (base name: "initiator")', function() {
      // uncomment below and update the code to test the property initiator
      //var instane = new FirstApiSdk.StoredCredential();
      //expect(instance).to.be();
    });

  });

}));
