/**
 * Payment Gateway API Specification
 * Payment Gateway API for payment processing. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FirstApiSdk);
  }
}(this, function(expect, FirstApiSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FirstApiSdk.TransactionResponseAuthenticationRedirectParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionResponseAuthenticationRedirectParams', function() {
    it('should create an instance of TransactionResponseAuthenticationRedirectParams', function() {
      // uncomment below and update the code to test TransactionResponseAuthenticationRedirectParams
      //var instane = new FirstApiSdk.TransactionResponseAuthenticationRedirectParams();
      //expect(instance).to.be.a(FirstApiSdk.TransactionResponseAuthenticationRedirectParams);
    });

    it('should have the property paReq (base name: "PaReq")', function() {
      // uncomment below and update the code to test the property paReq
      //var instane = new FirstApiSdk.TransactionResponseAuthenticationRedirectParams();
      //expect(instance).to.be();
    });

    it('should have the property termUrl (base name: "TermUrl")', function() {
      // uncomment below and update the code to test the property termUrl
      //var instane = new FirstApiSdk.TransactionResponseAuthenticationRedirectParams();
      //expect(instance).to.be();
    });

    it('should have the property MD (base name: "MD")', function() {
      // uncomment below and update the code to test the property MD
      //var instane = new FirstApiSdk.TransactionResponseAuthenticationRedirectParams();
      //expect(instance).to.be();
    });

  });

}));
